version: '3.8'

services:
  ruler-app:
    build: .
    container_name: ruler-web-app
    ports:
      - "5173:5173" # Map port 3000 on host to container
    restart: always # Automatically restart the container if it stops
    volumes:
      - .:/app # Mount project directory for live updates
    environment:
      - NODE_ENV=production

