version: '3.8'

services:
  ruler-app:
    build: .
    container_name: ruler-web-app
    ports:
      - "32141:5173" # Map port 32141 on the host to port 5173 in the container
    restart: always # Automatically restart the container if it stops
    volumes:
      - .:/app # Mount project directory for live updates
    environment:
      - NODE_ENV=production

